---
title: "Pivot Tables with dplyr"
format: html
editor: visual
---


```{r, include=FALSE, echo=FALSE}
## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')
```

```{r, echo=FALSE}

# import and Skip 4 line in the Excel File
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)

# explore data
# skimr::skim(lobsters) 
```

```{r, echo=FALSE}
lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_year = n())
```

```{r, echo=FALSE}
lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm=TRUE), 
            sd_size_mm = sd(size_mm, na.rm=TRUE))

## `summarise()` regrouping output by 'site' (override with `.groups` argument)
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE), 
            sd_size_mm = sd(size_mm, na.rm = TRUE), 
            median_size_mm = median(size_mm, na.rm = TRUE), )

## make a table with our new variable
siteyear_summary %>%
  kable()
```
There are `r nrow(lobsters)` total lobsters included in this report.

```{r, echo=FALSE}
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE), 
            sd_size_mm = sd(size_mm, na.rm = TRUE), 
            median_size_mm = median(size_mm, na.rm = TRUE))


## a ggplot option:
ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm, color = site)) +
  geom_line()

## Saving 7 x 5 in image

ggsave(here("figures", "lobsters-line.png"))

## another option:
ggplot(siteyear_summary, aes(x = year, y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)

ggsave(here("figures", "lobsters-col.png"))

## a ggplot option:
ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm, color = site)) +
  geom_line() 
```
## `summarise()` regrouping output by 'site' (override with `.groups` argument)

```{r echo=FALSE}
ggsave(here("figures", "lobsters-line.png"))

## another option:
ggplot(siteyear_summary, aes(x = year, y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)

ggsave(here("figures", "lobsters-col.png"))
```