---
title: "Creating graphs in R with `ggplot2`"
author: "Mulugeta Maru"
date: "2022-11-10"
output: html_document
---

# Plots with ggplot2

We are going to make plots in R and it's going to be amazing.

```{r include=FALSE, echo=FALSE}
library(tidyverse)
library(readxl)
library(here)
```

```{r echo=FALSE}
ca_np <- read_csv(here("data", "ca_np.csv"))
ci_np <- read_excel(here("data", "ci_np.xlsx"))

gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))

gg_base + geom_line(color = "purple",linetype = "dashed")
gg_base + geom_line(linetype = "dotted") + theme_bw() + labs(x = "Year",
    y = "Annual park visitors", title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  )
# As long as the geoms are compatible, we can layer them on top of one another to further customize a graph
gg_base + geom_line(color = "purple") + geom_point(color = "orange", aes(size = year),
             alpha = 0.5)

# gg_base + geom_point(color = "purple", pch = 17, size = 4, alpha = 0.5)
gg_base + geom_point(aes(size = visitors, color = visitors), alpha = 0.5) +
  theme_minimal()

# gg_base + geom_col()
gg_base + geom_col(aes(fill = visitors))
gg_base + geom_col(fill = "orange",color = "purple") + geom_line(color = "green")

gg_base + geom_area()

# ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name)) +
  geom_line()

gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))

gg_np + geom_line(show.legend = FALSE) + theme_light() + labs(x = "year", y = "annual visitors") + facet_wrap(~ park_name)

# Save a graph

ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)
```



